version: '3'

services:
  absolutewebservice:
    build: .
    ports:
      - 80:8080
    volumes:
      - /absolutewebservice/conf/conf.properties:app/conf/conf.properties
    networks: 
      - webapp
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_HOST=postgres  
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
    volumes:
      - /absolutewebservice/postgres:/var/lib/postgresql/data
    networks:
      - webapp
networks:
  webapp:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.11.0/24